In [13]:
import numpy as np
 np.empty((5,5))


IndentationError: unexpected indent (<ipython-input-13-1432fac17e5f>, line 2)

In [5]:
l = [1, 4, 5, 7]


In [6]:
np.array(l)

array([1, 4, 5, 7])

In [7]:
x = np.arange(1,100,10)

In [9]:
x = np.zeros((10,10))

In [10]:
x.shape

(10, 10)

In [11]:
y = x.reshape((2,2,5,5))

In [12]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [14]:
y.dtype

dtype('float64')

In [15]:
import numpy as np

In [19]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
np.empty((7,7))

array([[7.97841717e-312, 7.97859107e-312, 5.92878775e-321,
        1.97626258e-323, 4.98018171e-321, 9.85330308e+165,
        4.34777768e-321],
       [1.43573442e-023, 5.11852009e-321, 9.89803212e+164,
        5.19757059e-321, 9.08254074e+223, 5.23709585e-321,
        4.91510616e-062],
       [3.10273226e-321, 6.19941833e-071, 5.90902512e-321,
        9.16281075e-072, 5.92878775e-321, 9.45956165e-076,
        6.00783825e-321],
       [1.74226821e-152, 5.98807563e-321, 1.26111147e-052,
        2.86558075e-321, 1.76540626e+137, 5.92878775e-321,
        2.51698598e+145],
       [9.45956265e-076, 9.16281387e-072, 5.20806037e+045,
        9.75025264e+199, 2.14392305e+137, 9.02193423e+217,
        6.19941898e-071],
       [2.95153379e-075, 1.54152961e+256, 5.28758935e+180,
        6.96407958e+252, 6.11136196e+223, 1.81703471e+223,
        4.82406564e+228],
       [4.31814724e-096, 5.49914502e-143, 4.27148480e+180,
        6.01718272e+175, 3.13422195e+233, 7.28079528e+223,
        7.99196075

In [25]:
np.empty((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
import numpy as np

In [28]:
a

NameError: name 'a' is not defined

In [29]:
np.empty((5,6))

array([[7.97858085e-312, 9.78249979e-322, 0.00000000e+000,
        0.00000000e+000, 3.12450513e-033, 5.02034658e+175],
       [2.82892288e-056, 4.23120417e+175, 1.54646791e-075,
        7.71799477e-043, 5.34640159e-038, 3.59751658e+252],
       [8.93185432e+271, 4.76484771e+180, 1.47763641e+248,
        1.16096346e-028, 7.69165785e+218, 1.35617292e+248],
       [2.03274453e+160, 1.55030472e+184, 4.67124887e-062,
        7.12193722e-067, 5.43084740e-143, 1.16097020e-028],
       [6.37112413e-067, 9.72390516e-067, 1.40107682e-076,
        1.11763122e+261, 1.16318408e-028, 4.32089264e-086]])

In [30]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.34233597 0.43943059 0.36515114 0.52941296 0.75132741]
 [0.55841201 0.60468447 0.81700809 0.66331386 0.42280442]
 [0.10409702 0.25511268 0.57447087 0.25228513 0.96634402]
 [0.62849958 0.54471512 0.70466163 0.53801664 0.59010468]
 [0.48469676 0.56587469 0.72104084 0.56756627 0.50873435]]
Minimum and Maximum Values:
0.1040970198525295 0.9663440199191514


In [31]:
x**2

array([[0.11719392, 0.19309924, 0.13333536, 0.28027808, 0.56449287],
       [0.31182398, 0.3656433 , 0.66750222, 0.43998528, 0.17876358],
       [0.01083619, 0.06508248, 0.33001678, 0.06364779, 0.93382076],
       [0.39501172, 0.29671456, 0.49654802, 0.2894619 , 0.34822353],
       [0.23493095, 0.32021416, 0.5198999 , 0.32213147, 0.25881064]])

In [33]:
import numpy as np
x = np.random.random((5,6))
print('Original Array:')
print(x)

Original Array:
[[0.15982562 0.19024991 0.75901171 0.14784029 0.41467075 0.85223413]
 [0.00880155 0.88632542 0.56148182 0.43753052 0.52963621 0.00486432]
 [0.04870044 0.16565549 0.78287229 0.71318522 0.267732   0.89293262]
 [0.64683583 0.23162567 0.23460849 0.27548233 0.37160026 0.20086379]
 [0.50101421 0.99340746 0.26608587 0.99758029 0.88897238 0.85025588]]


In [34]:
np.mean(x)

0.4760627591314288

In [35]:
np.median(x)

0.42610063193377284

In [37]:
np.std(x)

0.31361151338637966

In [38]:
np.transpose(x)

array([[0.15982562, 0.00880155, 0.04870044, 0.64683583, 0.50101421],
       [0.19024991, 0.88632542, 0.16565549, 0.23162567, 0.99340746],
       [0.75901171, 0.56148182, 0.78287229, 0.23460849, 0.26608587],
       [0.14784029, 0.43753052, 0.71318522, 0.27548233, 0.99758029],
       [0.41467075, 0.52963621, 0.267732  , 0.37160026, 0.88897238],
       [0.85223413, 0.00486432, 0.89293262, 0.20086379, 0.85025588]])

In [39]:
import numpy as np
x = np.random.random((4,4))
print('Original Array:')
print(x)

Original Array:
[[0.07244439 0.39294521 0.90777495 0.3072803 ]
 [0.78682779 0.06245628 0.97271196 0.03684509]
 [0.05178494 0.03958046 0.23292575 0.07971715]
 [0.82686314 0.95468361 0.98933291 0.23312849]]


ValueError: invalid number of arguments

In [41]:
numpy.diagonal(a, offset=0, axis1=0, axis2=1

SyntaxError: unexpected EOF while parsing (<ipython-input-41-fa7ca0835123>, line 1)